version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "8005:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: task-manager-adminer
    restart: unless-stopped
    ports:
      - "8085:8080" # Host port 8085 -> Adminer port 8080

volumes:
  mysql_data:
